### ISSUE TITLE
server fails on any external data files provided on interface

### ISSUE THREAD

**Issue by 2sn** [2sn/starfit-server#24]
@conradtchan @dliptai 
I uploaded the original data file from starfit and sill get this error message.  It seems at this point no external data whatsoever works.  They all work ion the PyPI version.  (and we know this from tests)
```
Sorry... Your job was unsuccessful 😔

Job status: failed

Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1075, in perform_job
rv = job.perform()
File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 854, in perform
self._result = self._execute()
File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 877, in _execute
result = self.func(*self.args, **self.kwargs)
File "/var/www/html/./job.py", line 192, in run_job
result = compute(config)
File "/var/www/html/./job.py", line 54, in compute
result = starfit.Single(
File "/usr/local/lib64/python3.10/site-packages/starfit/fit.py", line 38, in __init__
self._setup(
File "/usr/local/lib64/python3.10/site-packages/starfit/starfit.py", line 91, in _setup
star = Star(filename, silent=self.silent)
File "/usr/local/lib64/python3.10/site-packages/starfit/read.py", line 72, in __init__
raise IOError(f"file {filename} not found")
OSError: file /tmp/HE1327-2326.dat2022-23-18-03-23-16 not found
```
I ran this on `starfit.xyz` but the main page seems the same.

**Comment by dliptai** [comment]
I think this might be because the workers have a private `/tmp/` space.
https://github.com/ADACS-Australia/starfit-server/blob/7dfe2b70bd429624020e9e6e155354edd7569bd8/roles/rq/files/rq-worker%40.service#L1-L19

**Comment by dliptai** [comment]
Fixed in 142fa7aca74deb525be302c5ffab9851cac347b8

**Comment by 2sn** [comment]
@dliptai we try out on `starfit.xyz`?

**Comment by dliptai** [comment]
Yep I've just deployed it

**Comment by 2sn** [comment]
@david but it does not work for me on `starfi.xyz`

**Comment by dliptai** [comment]
yeh i think there's more issues
just pushed another fix 2fc12bbe380fb3728961944d2a7f00fcbf018382

**Comment by 2sn** [comment]
You can try by just using the `*.dat` file from the python package.

**Comment by dliptai** [comment]
ahh I think `apache` is also using a private `/tmp`

**Comment by 2sn** [comment]
@dliptai I am trying again on `satrfit.xyz` but seems to be still out.  I can't easily see what version is there, though.  

At some point there had been a plan to put a git hash as version of the server, but with the different deploy scripts that may be no longer possible ro obvious.

**Comment by dliptai** [comment]
There is a `Deployment Info` link at the bottom of the page. Implemented in 3add5493a3062e0e75cd19debdc912a02cd7a4f7

**Comment by 2sn** [comment]
I see.  Excellent.  thanks!

**Comment by dliptai** [comment]
Fixed and deployed now. Seems to work.
Just needed make sure RQ workers and Apache were sharing the same /tmp
60088c04e68540dd7238ff46f72bd32c180f68ff

**Comment by 2sn** [comment]
seems to fail for most other models.
```
Sorry... Your job was unsuccessful 😔

Job status: failed

Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1075, in perform_job
rv = job.perform()
File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 854, in perform
self._result = self._execute()
File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 877, in _execute
result = self.func(*self.args, **self.kwargs)
File "/var/www/html/./job.py", line 193, in run_job
imgfiles = make_plots(result, config)
File "/var/www/html/./job.py", line 77, in make_plots
result.plot()
File "/usr/local/lib64/python3.10/site-packages/starfit/starfit.py", line 417, in plot
self.labels, self.plotdata = starplot.abuplot(
File "/usr/local/lib64/python3.10/site-packages/starfit/starplot.py", line 388, in abuplot
ax.errorbar(
File "/usr/local/lib64/python3.10/site-packages/matplotlib/__init__.py", line 1423, in inner
return func(ax, *map(sanitize_sequence, args), **kwargs)
File "/usr/local/lib64/python3.10/site-packages/matplotlib/axes/_axes.py", line 3587, in errorbar
raise ValueError(
ValueError: 'yerr' must not contain negative values
```
but I need to check this off-line with installed `starfit`

**Comment by 2sn** [comment]
@dliptai So I think you fix takes care of the external file issue.  So we may close this.

**Comment by 2sn** [comment]
@dliptai Thanks!!!

**Comment by 2sn** [comment]
Hmm, I am seeing this again on `starfit.xyz`, but I admit to having replaced `os.path` by `pathlib.Path`
```
Sorry... Your job was unsuccessful 😔

Job status: failed

Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1075, in perform_job
rv = job.perform()
File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 854, in perform
self._result = self._execute()
File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 877, in _execute
result = self.func(*self.args, **self.kwargs)
File "/var/www/html/./job.py", line 194, in run_job
result = compute(config)
File "/var/www/html/./job.py", line 56, in compute
result = Single(
File "/usr/local/lib64/python3.10/site-packages/starfit/single.py", line 31, in __init__
self._setup(
File "/usr/local/lib64/python3.10/site-packages/starfit/starfit.py", line 174, in _setup
star = Star(filename, silent=self.silent)
File "/usr/local/lib64/python3.10/site-packages/starfit/star.py", line 72, in __init__
filename = find_data(STARS, filename)
File "/usr/local/lib64/python3.10/site-packages/starfit/utils.py", line 39, in find_data
raise IOError(f"file {filename} not found")
OSError: file /tmp/HE1327-2326.dat2022-50-24-08-50-09 not found
```
I am trying to debug it, but I can make absolutely no sense of it.  If I add a debug statement in the server's `utils.py` I get
```
Exception	Python 3.10.7: /usr/bin/python
Mon Oct 24 10:07:26 2022
A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.

 /var/www/html/run in <module>
     19 
     20 forms = cgi.FieldStorage()  # Retrieve form fields
=>   21 config = Config(forms)  # Validate form fields and generate config
     22 ip = os.environ["REMOTE_ADDR"]
     23 
config undefined, Config = <class 'utils.Config'>, forms = FieldStorage(None, None, [FieldStorage('algorith...e, ''), FieldStorage('plotformat', None, 'png')])
 /var/www/html/utils.py in __init__(self=<utils.Config object>, form=FieldStorage(None, None, [FieldStorage('algorith...e, ''), FieldStorage('plotformat', None, 'png')]))
     82             with open(filepath, "wb") as fstar:
     83                 fstar.write(stardata.file.read())
=>   84             raise Exception(f'xxx: {filepath}, {glob("/tmp/*")}')
     85             filename = stardata.filename
     86         else:
builtin Exception = <class 'Exception'>
Exception: xxx: /tmp/HE1327-2326.dat2022-07-24-10-07-26, ['/tmp/HE1327-2326.dat2022-07-24-10-07-26', '/tmp/HE1327-2326.dat2022-01-24-10-01-58', '/tmp/HE1327-2326.dat2022-55-24-09-55-22', '/tmp/HE1327-2326.dat2022-51-24-09-51-33', '/tmp/HE1327-2326.dat2022-50-24-09-50-58', '/tmp/HE1327-2326.dat2022-42-24-09-42-07', '/tmp/HE1327-2326.dat2022-50-24-08-50-09', '/tmp/smss2003-1142.txt2022-48-24-08-48-41', '/tmp/plot_data_points2022-01-22-15-01-45', '/tmp/2022-01-22-15-01-45', '/tmp/plot_data_points2022-54-22-14-54-48', '/tmp/2022-54-22-14-54-48', '/tmp/plot_data_points2022-50-22-14-50-49', '/tmp/2022-50-22-14-50-49', '/tmp/plot_data_points2022-33-22-14-33-23', '/tmp/plot_data_points2022-24-22-13-24-32', '/tmp/plot_data_points2022-23-22-13-23-55', '/tmp/2022-23-22-13-23-55', '/tmp/plot_data_points2022-23-22-13-23-18', '/tmp/plot_data_points2022-22-22-13-22-47', '/tmp/plot_data_points2022-21-22-13-21-47', '/tmp/2022-21-22-13-21-47', '/tmp/plot_data_points2022-20-22-13-20-00', '/tmp/plot_data_points2022-32-21-03-32-41', '/tmp/starfit_snapshot_075_star_002.txt2022-32-21-03-32-41', '/tmp/plot_data_points2022-31-21-03-31-01', '/tmp/starfit_snapshot_075_star_002.txt2022-31-21-03-31-01', '/tmp/plot_data_points2022-30-21-03-30-27', '/tmp/starfit_snapshot_075_star_000.txt2022-30-21-03-30-27', '/tmp/plot_data_points2022-29-21-03-29-33', '/tmp/starfit_snapshot_075_star_000.txt2022-29-21-03-29-33', '/tmp/plot_data_points2022-29-21-03-29-13', '/tmp/starfit_snapshot_075_star_000.txt2022-29-21-03-29-13', '/tmp/plot_data_points2022-21-21-03-21-48', '/tmp/starfit_snapshot_075_star_002.txt2022-21-21-03-21-48', '/tmp/plot_data_points2022-53-21-02-53-22', '/tmp/starfit_snapshot_075_star_002.txt2022-53-21-02-53-22', '/tmp/plot_data_points2022-53-21-02-53-08', '/tmp/starfit_snapshot_075_star_001.txt2022-53-21-02-53-08', '/tmp/plot_data_points2022-52-21-02-52-58', '/tmp/starfit_snapshot_075_star_000.txt2022-52-21-02-52-58', '/tmp/plot_data_points2022-51-21-02-51-31', '/tmp/starfit_snapshot_075_star_002.txt2022-51-21-02-51-31', '/tmp/plot_data_points2022-51-21-02-51-22', '/tmp/starfit_snapshot_075_star_001.txt2022-51-21-02-51-22', '/tmp/plot_data_points2022-51-21-02-51-10', '/tmp/starfit_snapshot_075_star_000.txt2022-51-21-02-51-10', '/tmp/plot_data_points2022-34-20-23-34-34', '/tmp/smss2003-1142.txt2022-34-20-23-34-34', '/tmp/plot_data_points2022-34-20-23-34-23', '/tmp/smss2003-1142.txt2022-34-20-23-34-23', '/tmp/plot_data_points2022-34-20-23-34-14', '/tmp/smss2003-1142.txt2022-34-20-23-34-14', '/tmp/smss2003-1142.txt2022-34-20-23-34-01', '/tmp/plot_data_points2022-33-20-23-33-53', '/tmp/smss2003-1142.txt2022-33-20-23-33-53', '/tmp/plot_data_points2022-33-20-23-33-40', '/tmp/smss2003-1142.txt2022-33-20-23-33-40', '/tmp/plot_data_points2022-33-20-23-33-30', '/tmp/smss2003-1142.txt2022-33-20-23-33-30', '/tmp/plot_data_points2022-29-20-23-29-17', '/tmp/smss2003.txt2022-29-20-23-29-17', '/tmp/plot_data_points2022-26-20-23-26-53', '/tmp/smss2003.txt2022-26-20-23-26-53', '/tmp/plot_data_points2022-26-20-23-26-38', '/tmp/smss2003.txt2022-26-20-23-26-38', '/tmp/plot_data_points2022-25-20-23-25-59', '/tmp/smss2003.txt2022-25-20-23-25-59', '/tmp/plot_data_points2022-25-20-23-25-33', '/tmp/smss2003.txt2022-25-20-23-25-33', '/tmp/rproc.just15.star.el.y.stardb.xz2022-43-20-08-43-27', '/tmp/rproc.just15.star.el.y.stardb.xz2022-43-20-08-43-15', '/tmp/rproc.just15.star.el.y.stardb.xz2022-42-20-08-42-59', '/tmp/plot_data_points2022-59-20-07-59-31', '/tmp/starfit_snapshot_100_star_007.txt2022-59-20-07-59-31', '/tmp/plot_data_points2022-59-20-07-59-17', '/tmp/starfit_snapshot_100_star_006.txt2022-59-20-07-59-17', '/tmp/plot_data_points2022-59-20-07-59-06', '/tmp/starfit_snapshot_100_star_005.txt2022-59-20-07-59-06', '/tmp/plot_data_points2022-58-20-07-58-56', '/tmp/starfit_snapshot_100_star_004.txt2022-58-20-07-58-56', '/tmp/plot_data_points2022-58-20-07-58-32', '/tmp/starfit_snapshot_100_star_003.txt2022-58-20-07-58-32', '/tmp/plot_data_points2022-58-20-07-58-18', '/tmp/starfit_snapshot_100_star_001.txt2022-58-20-07-58-18', '/tmp/plot_data_points2022-58-20-07-58-07', '/tmp/starfit_snapshot_100_star_000.txt2022-58-20-07-58-07', '/tmp/plot_data_points2022-57-20-07-57-56', '/tmp/starfit_snapshot_100_star_007.txt2022-57-20-07-57-56', '/tmp/plot_data_points2022-57-20-07-57-46', '/tmp/starfit_snapshot_100_star_006.txt2022-57-20-07-57-46', '/tmp/plot_data_points2022-57-20-07-57-36', '/tmp/starfit_snapshot_100_star_005.txt2022-57-20-07-57-36', '/tmp/plot_data_points2022-57-20-07-57-26', '/tmp/starfit_snapshot_100_star_004.txt2022-57-20-07-57-26', '/tmp/plot_data_points2022-57-20-07-57-14', '/tmp/starfit_snapshot_100_star_003.txt2022-57-20-07-57-14', '/tmp/plot_data_points2022-56-20-07-56-56', '/tmp/starfit_snapshot_100_star_002.txt2022-56-20-07-56-56', '/tmp/plot_data_points2022-56-20-07-56-33', '/tmp/starfit_snapshot_100_star_001.txt2022-56-20-07-56-33', '/tmp/plot_data_points2022-56-20-07-56-22', '/tmp/starfit_snapshot_100_star_000.txt2022-56-20-07-56-22', '/tmp/plot_data_points2022-54-20-07-54-15', '/tmp/starfit_snapshot_100_star_000.txt2022-54-20-07-54-15', '/tmp/plot_data_points2022-51-20-07-51-04', '/tmp/starfit_snapshot_100_star_000.txt2022-51-20-07-51-04', '/tmp/starfit_snapshot_100_star_000.txt2022-50-20-07-50-27', '/tmp/starfit_snapshot_100_star_000.txt2022-49-20-07-49-25', '/tmp/plot_data_points2022-17-20-07-17-57', '/tmp/plot_data_points2022-00-20-07-00-19', '/tmp/plot_data_points2022-21-20-06-21-18', '/tmp/plot_data_points2022-20-20-06-20-56', '/tmp/plot_data_points2022-18-20-06-18-54', '/tmp/plot_data_points2022-55-20-04-55-56', '/tmp/j1023sn.dat2022-55-20-04-55-56', '/tmp/plot_data_points2022-55-20-04-55-43', '/tmp/j1023sn.dat2022-55-20-04-55-43', '/tmp/plot_data_points2022-55-20-04-55-33', '/tmp/j1023sn.dat2022-55-20-04-55-33', '/tmp/plot_data_points2022-55-20-04-55-04', '/tmp/j1023sn.dat2022-55-20-04-55-04', '/tmp/plot_data_points2022-54-20-04-54-52', '/tmp/j1023sn.dat2022-54-20-04-54-52', '/tmp/plot_data_points2022-54-20-04-54-40', '/tmp/j1023sn.dat2022-54-20-04-54-40', '/tmp/plot_data_points2022-54-20-04-54-24', '/tmp/j1023sn.dat2022-54-20-04-54-24', '/tmp/plot_data_points2022-54-20-04-54-11', '/tmp/j1023sn.dat2022-54-20-04-54-11', '/tmp/plot_data_points2022-53-20-04-53-57', '/tmp/j1023sn.dat2022-53-20-04-53-57', '/tmp/plot_data_points2022-53-20-04-53-39', '/tmp/j1023sn.dat2022-53-20-04-53-39', '/tmp/plot_data_points2022-50-20-04-50-19', '/tmp/j1023sn.dat2022-50-20-04-50-19', '/tmp/plot_data_points2022-50-20-04-50-03', '/tmp/j1023sn.dat2022-50-20-04-50-03', '/tmp/plot_data_points2022-49-20-04-49-27', '/tmp/j1023sn.dat2022-49-20-04-49-27', '/tmp/plot_data_points2022-48-20-04-48-26', '/tmp/j1023sn.dat2022-48-20-04-48-26', '/tmp/plot_data_points2022-47-20-04-47-52', '/tmp/j1023sn.dat2022-47-20-04-47-52', '/tmp/plot_data_points2022-47-20-04-47-25', '/tmp/j1023sn.dat2022-47-20-04-47-25', '/tmp/plot_data_points2022-47-20-04-47-02', '/tmp/j1023sn.dat2022-47-20-04-47-02', '/tmp/plot_data_points2022-44-20-04-44-47', '/tmp/j1023sn.dat2022-44-20-04-44-47', '/tmp/plot_data_points2022-35-20-04-35-46', '/tmp/plot_data_points2022-35-20-04-35-12', '/tmp/plot_data_points2022-34-20-04-34-00', '/tmp/plot_data_points2022-31-20-04-31-52', '/tmp/plot_data_points2022-13-20-04-13-42', '/tmp/plot_data_points2022-10-20-04-10-33', '/tmp/plot_data_points2022-50-20-01-50-00', '/tmp/plot_data_points2022-48-20-01-48-52', '/tmp/plot_data_points2022-48-20-01-48-20', '/tmp/plot_data_points2022-40-20-01-40-49', '/tmp/plot_data_points2022-40-20-01-40-18', '/tmp/plot_data_points2022-36-20-01-36-00', '/tmp/plot_data_points2022-34-20-01-34-01', '/tmp/plot_data_points2022-31-20-01-31-45', '/tmp/rproc.just15.star.el.y.stardb.xz2022-54-19-22-54-40', '/tmp/rproc.just15.star.el.y.stardb.xz2022-48-19-22-48-02', '/tmp/plot_data_points2022-21-19-21-21-47', '/tmp/plot_data_points2022-21-19-21-21-12', '/tmp/plot_data_points2022-11-19-19-11-52', '/tmp/starfit.el2022-11-19-19-11-52', '/tmp/plot_data_points2022-10-19-17-10-54', '/tmp/plot_data_points2022-08-19-17-08-47', '/tmp/plot_data_points2022-09-19-15-09-33', '/tmp/j1023sn.dat2022-09-19-15-09-33', '/tmp/plot_data_points2022-14-19-14-14-57', '/tmp/j1023sn.dat2022-14-19-14-14-57', '/tmp/plot_data_points2022-12-19-14-12-18', '/tmp/j1023sn.dat2022-12-19-14-12-18', '/tmp/plot_data_points2022-11-19-14-11-50', '/tmp/j1023sn.dat2022-11-19-14-11-50', '/tmp/plot_data_points2022-11-19-14-11-22', '/tmp/j1023sn.dat2022-11-19-14-11-22', '/tmp/plot_data_points2022-11-19-14-11-09', '/tmp/j1023sn.dat2022-11-19-14-11-09', '/tmp/plot_data_points2022-10-19-14-10-38', '/tmp/j1023sn.dat2022-10-19-14-10-38', '/tmp/plot_data_points2022-10-19-14-10-03', '/tmp/j1023sn.dat2022-10-19-14-10-03', '/tmp/plot_data_points2022-09-19-14-09-47', '/tmp/j1023sn.dat2022-09-19-14-09-47', '/tmp/plot_data_points2022-09-19-14-09-10', '/tmp/j1023sn.dat2022-09-19-14-09-10', '/tmp/plot_data_points2022-07-19-14-07-59', '/tmp/j1023sn.dat2022-07-19-14-07-59', '/tmp/plot_data_points2022-03-19-13-03-36', '/tmp/j1023sn.dat2022-03-19-13-03-36', '/tmp/plot_data_points2022-02-19-13-02-56', '/tmp/j1023sn.dat2022-02-19-13-02-56', '/tmp/plot_data_points2022-47-19-12-47-27', '/tmp/j1023sn.dat2022-47-19-12-47-27', '/tmp/plot_data_points2022-45-19-12-45-36', '/tmp/j1023sn.dat2022-45-19-12-45-36', '/tmp/plot_data_points2022-44-19-12-44-53', '/tmp/j1023sn.dat2022-44-19-12-44-53', '/tmp/plot_data_points2022-43-19-12-43-48', '/tmp/j1023sn.dat2022-43-19-12-43-48', '/tmp/plot_data_points2022-39-19-12-39-23', '/tmp/j1023sn.dat2022-39-19-12-39-23', '/tmp/plot_data_points2022-37-19-12-37-42', '/tmp/j1023sn.dat2022-37-19-12-37-42', '/tmp/j1023sn.dat2022-35-19-12-35-05', '/tmp/j1023sn.dat2022-33-19-12-33-53', '/tmp/plot_data_points2022-14-19-09-14-11', '/tmp/xing2023_priv.txt2022-14-19-09-14-11', '/tmp/plot_data_points2022-12-19-09-12-36', '/tmp/xing2023_priv.txt2022-12-19-09-12-36', '/tmp/plot_data_points2022-11-19-09-11-01', '/tmp/xing2023_priv.txt2022-11-19-09-11-01', '/tmp/plot_data_points2022-10-19-09-10-40', '/tmp/xing2023_priv.txt2022-10-19-09-10-40', '/tmp/plot_data_points2022-09-19-09-09-56', '/tmp/xing2023_priv.txt2022-09-19-09-09-56', '/tmp/plot_data_points2022-03-19-09-03-26', '/tmp/xing2023_priv.txt2022-03-19-09-03-26', '/tmp/plot_data_points2022-02-19-09-02-59', '/tmp/xing2023_priv.txt2022-02-19-09-02-59', '/tmp/plot_data_points2022-02-19-09-02-03', '/tmp/xing2023_priv.txt2022-02-19-09-02-03', '/tmp/plot_data_points2022-00-19-09-00-29', '/tmp/xing2023_priv.txt2022-00-19-09-00-29', '/tmp/plot_data_points2022-59-19-08-59-59', '/tmp/xing2023_priv.txt2022-59-19-08-59-59', '/tmp/plot_data_points2022-59-19-08-59-39', '/tmp/xing2023_priv.txt2022-59-19-08-59-39', '/tmp/plot_data_points2022-57-19-08-57-51', '/tmp/xing2023_priv.txt2022-57-19-08-57-51', '/tmp/plot_data_points2022-57-19-08-57-21', '/tmp/xing2023_priv.txt2022-57-19-08-57-21', '/tmp/plot_data_points2022-56-19-08-56-44', '/tmp/xing2023_priv.txt2022-56-19-08-56-44', '/tmp/plot_data_points2022-53-19-08-53-07', '/tmp/xing2023_priv.txt2022-53-19-08-53-07', '/tmp/xing2023_priv.txt2022-52-19-08-52-41', '/tmp/plot_data_points2022-45-19-07-45-50', '/tmp/plot_data_points2022-09-19-05-09-23', '/tmp/plot_data_points2022-24-19-02-24-25', '/tmp/plot_data_points2022-23-19-02-23-03', '/tmp/plot_data_points2022-21-19-02-21-17', '/tmp/plot_data_points2022-56-19-01-56-17', '/tmp/starfit_snapshot_100_star_002.txt2022-56-19-01-56-17', '/tmp/plot_data_points2022-50-18-14-50-42', '/tmp/starfit_snapshot_100_star_001.txt2022-50-18-14-50-42', '/tmp/plot_data_points2022-02-18-14-02-48', '/tmp/starfit_snapshot_100_star_002.txt2022-02-18-14-02-48', '/tmp/plot_data_points2022-52-18-13-52-25', '/tmp/starfit.y2022-52-18-13-52-25', '/tmp/plot_data_points2022-50-18-13-50-55', '/tmp/starfit.y2022-50-18-13-50-55', '/tmp/plot_data_points2022-50-18-13-50-10', '/tmp/starfit.y2022-50-18-13-50-10', '/tmp/plot_data_points2022-49-18-13-49-00', '/tmp/starfit.y2022-49-18-13-49-00', '/tmp/plot_data_points2022-48-18-13-48-01', '/tmp/starfit.y2022-48-18-13-48-01', '/tmp/plot_data_points2022-00-18-13-00-09', '/tmp/BD_80_245.dat2022-00-18-13-00-09', '/tmp/plot_data_points2022-59-18-12-59-37', '/tmp/BD_80_245.dat2022-59-18-12-59-37', '/tmp/plot_data_points2022-59-18-12-59-21', '/tmp/BD_80_245.dat2022-59-18-12-59-21', '/tmp/plot_data_points2022-59-18-12-59-01', '/tmp/BD_80_245.dat2022-59-18-12-59-01', '/tmp/plot_data_points2022-57-18-12-57-55', '/tmp/BD_80_245.dat2022-57-18-12-57-55', '/tmp/plot_data_points2022-57-18-12-57-36', '/tmp/BD_80_245.dat2022-57-18-12-57-36', '/tmp/plot_data_points2022-55-18-12-55-06', '/tmp/BD_80_245.dat2022-55-18-12-55-06', '/tmp/BD_80_245.dat2022-52-18-07-52-39', '/tmp/BD_80_245.dat2022-43-18-07-43-39', '/tmp/BD_80_245.dat2022-43-18-07-43-33', '/tmp/plot_data_points2022-41-18-07-41-57', '/tmp/plot_data_points2022-41-18-07-41-37', '/tmp/plot_data_points2022-30-18-06-30-41', '/tmp/HE1327-2326.dat2022-30-18-06-30-41', '/tmp/HE1424-0241.dat2022-30-18-06-30-26', '/tmp/HE1424-0241.dat2022-28-18-06-28-55', '/tmp/plot_data_points2022-28-18-06-28-11', '/tmp/SDSS-J102915+172927.dat2022-28-18-06-28-11', '/tmp/plot_data_points2022-27-18-06-27-14', '/tmp/SMSS_J031300-670839.dat2022-27-18-06-27-14', '/tmp/Cayrel2004.dat2022-25-18-06-25-23', '/tmp/HE0107-5240.dat2022-24-18-06-24-43', '/tmp/BS16934-002.dat2022-23-18-06-23-40', '/tmp/plot_data_points2022-23-18-06-23-14', '/tmp/HE1327-2326.dat2022-23-18-06-23-14', '/tmp/BS16934-002.dat2022-22-18-06-22-57', '/tmp/plot_data_points2022-21-18-06-21-46', '/tmp/HE1327-2326.dat2022-21-18-06-21-46', '/tmp/plot_data_points2022-20-18-06-20-50', '/tmp/starfit.blah.txt2022-20-18-06-20-50', '/tmp/plot_data_points2022-20-18-06-20-35', '/tmp/HE1327-2326.dat2022-20-18-06-20-35']
      args = ("xxx: /tmp/HE1327-2326.dat2022-07-24-10-07-26, ['...0-35', '/tmp/HE1327-2326.dat2022-20-18-06-20-35']",)
      with_traceback = <built-in method with_traceback of Exception object>
```
The essence being that there is many files in `/tmp` but when I do the same in `starfit`'s `utils.py` I get
```
 Sorry... Your job was unsuccessful 😔

Job status: failed

Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1075, in perform_job
rv = job.perform()
File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 854, in perform
self._result = self._execute()
File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 877, in _execute
result = self.func(*self.args, **self.kwargs)
File "/var/www/html/./job.py", line 194, in run_job
result = compute(config)
File "/var/www/html/./job.py", line 56, in compute
result = Single(
File "/usr/local/lib64/python3.10/site-packages/starfit/single.py", line 31, in __init__
self._setup(
File "/usr/local/lib64/python3.10/site-packages/starfit/starfit.py", line 174, in _setup
star = Star(filename, silent=self.silent)
File "/usr/local/lib64/python3.10/site-packages/starfit/star.py", line 72, in __init__
filename = find_data(STARS, filename)
File "/usr/local/lib64/python3.10/site-packages/starfit/utils.py", line 40, in find_data
raise IOError(f"file {filename} not found: {glob('/tmp/*')}")
OSError: file /tmp/HE1327-2326.dat2022-12-24-10-12-03 not found: ['/tmp/plot_data_points2022-23-23-15-23-52', '/tmp/2022-23-23-15-23-52']
```
The essence being, no files in `/tmp` - how can this be?  There is also no files when I do `ls` as root.  How is this all possible?  What am I not understanding about unix file systems?  Or is the server running in some virtual file system?

**Comment by 2sn** [comment]
@dliptai

**Comment by 2sn** [comment]
I re-installed the server with a full playbook and started `starfit.xyz` in a new tab, then it seemed to work.  I may have been the latter.  Something with too-smart web infrastructure, maybe?

**Comment by 2sn** [comment]
I leave you this for a though, if you have no ideas either, maybe just close it again.

**Comment by 2sn** [comment]
(very frustrating web server debugging)

**Comment by dliptai** [comment]
I'm pretty sure it's something to do with `PrivateTmp` feature of systemd services...
You can get some unexpected behaviour e.g. https://access.redhat.com/discussions/3027351

From the docs:

> PrivateTmp=
Takes a boolean argument. If true, sets up a new file system namespace for the executed processes and mounts private /tmp/ and /var/tmp/ directories inside it that are not shared by processes outside of the namespace. This is useful to secure access to temporary files of the process, but makes sharing between processes via /tmp/ or /var/tmp/ impossible. If true, all temporary files created by a service in these directories will be removed after the service is stopped. Defaults to false. It is possible to run two or more units within the same private /tmp/ and /var/tmp/ namespace by using the JoinsNamespaceOf= directive, see [systemd.unit(5)](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#) for details. This setting is implied if DynamicUser= is set. For this setting, the same restrictions regarding mount propagation and privileges apply as for ReadOnlyPaths= and related calls, see above. Enabling this setting has the side effect of adding Requires= and After= dependencies on all mount units necessary to access /tmp/ and /var/tmp/. Moreover an implicitly After= ordering on [systemd-tmpfiles-setup.service(8)](https://www.freedesktop.org/software/systemd/man/systemd-tmpfiles-setup.service.html#) is added.

> Note that the implementation of this setting might be impossible (for example if mount namespaces are not available), and the unit should be written in a way that does not solely rely on this setting for security.

> This option is only available for system services, or for services running in per-user instances of the service manager when PrivateUsers= is enabled.


To prevent any future problems you can just set `PrivateTmp=false` for the apache and rq worker services, but that may open up some security vulnerabilities (?)

**Comment by 2sn** [comment]
This seems to have resolved.
